groups/__init__.py
from flask import Blueprint

groups_blueprint = Blueprint("groups", __name__, template_folder="templates")

from . import views

groups/views.py
from . import groups_blueprint
from flask import request, redirect, url_for, render_template
from extensions import get_teams, get_permission_and_teams, get_container, random_id


@groups_blueprint.route("/group")
def write_group():
    cookie = request.cookies.get("workouts_permissions")
    permission, _ = get_permission_and_teams(cookie)

    if permission not in ["rw", "rwe"]:
        return redirect(url_for("index"), code=302)

    return render_template("group_writer.html", teams=get_teams())


@groups_blueprint.route("/group/<id>")
def write_group_id(id):
    cookie = request.cookies.get("workouts_permissions")
    permission, _ = get_permission_and_teams(cookie)

    if permission not in ["rw", "rwe"]:
        return redirect(url_for("index"), code=302)

    groups = get_container("groups").query_items(
        query=f"SELECT * FROM groups g WHERE g.id = '{id}'",
        enable_cross_partition_query=True,
    )

    real_group = {}
    for group in groups:
        real_group = group

    return render_template(
        "group_writer.html",
        id=real_group["id"],
        name=real_group["name"],
        code=real_group["code"],
        teams=get_teams(),
        team_id=real_group["team_id"],
    )


@groups_blueprint.route("/group", methods=["POST"])
def group():
    id = request.form.get("id")
    if not id:
        id = random_id()
    name = request.form.get("name")
    code = request.form.get("code")
    team = request.form.get("team")

    cookie = request.cookies.get("workouts_permissions")
    permission, team_ids = get_permission_and_teams(cookie)
    if (permission != "rw" and permission != "rwe") or team not in team_ids:
        return redirect(url_for("index"), code=301)

    get_container("groups").upsert_item(
        {"id": id, "name": name, "code": code, "team_id": team}
    )
    return redirect(url_for("write_group_id", id=id), code=301)

groups/templates/group_writer.html
{% extends 'base.html' %}
{% block links %}
<li><a href="{{ url_for('index') }}">home</a></li>
{% endblock %}
{% block content %}
<h1>{% block title %}writing a group{% endblock %}</h1>
{% if id %}
<p>editing</p>
{% endif %}
<form action={{ url_for('groups.group') }} method="post">
  <label style='display: none;' for='id'>id</label>
  <input style='display: none;' type='text' id='id' name='id' value='{{ id }}'><br />
  <label for='name'>name</label>
  <input type='text' id='name' name='name' value='{{ name }}'><br />
  <label for='code'>code</label>
  <input type='text' id='code' name='code' value='{{ code }}'><br />
  <label for='team'>team</label>
  <select name='team'>
    {% for team in teams %}
    {% if team['id'] == team_id %}
    <option value="{{ team['id'] }}" selected>{{ team['name'] }}</option>
    {% else %}
    <option value="{{ team['id'] }}">{{ team['name'] }}</option>
    {% endif %}
    {% endfor %}
  </select><br />
  <input type='submit' value='save'>
</form>
{% endblock %}